name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Push on Dockerhub
        run: docker push ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin < ~/password.txt
            docker pull ${{ secrets.DOCKER_IMAGE }}
            docker stop ${{ secrets.SERVER_NAME }}
            docker rm ${{ secrets.SERVER_NAME }}
            docker run -d --name ${{ secrets.SERVER_NAME }} -p 80:8080 --env-file .env ${{ secrets.DOCKER_IMAGE }}